#!/usr/bin/bash
echo "======= create bucket ======="

if [ -z "$1" ]; then
    echo "Provide bucket name"
    echo "Usage: $0 <argument>"
    exit 1
fi

aws s3api create-bucket --bucket $1 --query Location --output text

