#!/usr/bin/bash
set -e
echo "======= delete objects ========"

if [ -z "$1" ]; then
    echo "Provide bucket name"
    echo "Usage: $0 <argument>"
    exit 1
fi

BUCKET_NAME=$1

# This will put all the files in delete object json
# View the delete file by cat /tmp/delete_object.json
aws s3api list-objects-v2 --bucket $BUCKET_NAME --query Contents[].Key | jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_object.json


aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_object.json
