#!/usr/bin/bash
set -e
echo "======= list objects ========"

if [ -z "$1" ]; then
    echo "Provide bucket name"
    echo "Usage: $0 <argument>"
    exit 1
fi

BUCKET_NAME=$1


aws s3api list-objects-v2 --bucket $BUCKET_NAME